modernized the envscr a bit, mostly removing weird python stuff in favor of uv

diff --git a/envscr/install b/envscr/install
--- a/envscr/install
+++ b/envscr/install
@@ -6,7 +6,6 @@
 COMP=gcc
 MAKE_JOBCOUNT=8
 PYTHON_VERSION=3.8.2
-PYENV_VERSION=v2.0.0-rc1
 
 # ============================================================================
 # -- Do not modify below this line -------------------------------------------
@@ -52,8 +51,8 @@ if [ -z "${CMAKE}" ]; then
     if [ -z "${CMAKE}" ]; then
         err "'cmake' not found" && exit 1
         exit 1
-    elif [[ $( ${CMAKE} --version | cut -d " " -f 3 ) != [34]* ]]; then
-        err "CMake 3.x or 4.x is required to build VPR" && exit 1
+    elif [[ $( ${CMAKE} --version | cut -d " " -f 3 ) != [3]* ]]; then
+        err "CMake 3.x is required to build VPR" && exit 1
     fi
 fi
 info "Using 'cmake': ${CMAKE}"
@@ -65,48 +64,12 @@ if [ -z "${CC}" ]; then
 fi
 info "Using '${COMP}': ${CC}"
 
-# find or install pyenv
-if command -v pyenv 2>&1 >/dev/null; then
-    info "Active 'pyenv' found. Skipping installation/activation of 'pyenv'"
-else
-    if [ ! -f pyenv/bin/pyenv ]; then
-        info "'pyenv' not found. Installing 'pyenv' locally to ${PWD}/pyenv"
-        ${GIT} clone https://github.com/pyenv/pyenv.git || exit 1
-        cd pyenv && ${GIT} fetch && ${GIT} checkout ${PYENV_VERSION} && cd ..
-        info "'pyenv' installed locally to ${PWD}/pyenv"
-    else
-        info "Locally-installed 'pyenv' found. Updating 'pyenv'"
-        cd pyenv && ${GIT} fetch && ${GIT} checkout ${PYENV_VERSION} && cd ..
-        info "'pyenv' updated"
-    fi
-
-    info "Activating locally-installed 'pyenv'"
-    export PYENV_ROOT=${PWD}/pyenv
-    export PATH=${PYENV_ROOT}/bin:$PATH
-    eval "$( pyenv init --path )"
-    eval "$( pyenv init - )"
-    info "'pyenv' activated"
+# find uv
+UV=$( command -v uv 2>/dev/null )
+if [ -z "${UV}" ]; then
+    err "'uv' not found. Please ensure uv is installed." && exit 1
 fi
-
-# install the desired python if it's not installed already
-info "Installing Python ${PYTHON_VERSION} with 'pyenv'"
-env PYTHON_CONFIGURE_OPTS="--enable-shared" CFLAGS="-fPIC" CXXFLAGS="-fPIC" pyenv install -s ${PYTHON_VERSION} || exit 1
-info "Python ${PYTHON_VERSION} installed with 'pyenv'"
-pyenv local ${PYTHON_VERSION} || exit 1
-if [[ $( python --version | cut -d " " -f 2 ) != "${PYTHON_VERSION}" ]]; then
-    err "'pyenv' is not choosing the correct Python version" && exit 1
-fi
-info "Python ${PYTHON_VERSION} chosen as the local version"
-
-# upgrade pip and setuptools
-info "Upgrading 'pip' and 'setuptools'"
-pip install --upgrade setuptools pip
-info "'pip' and 'setuptools' upgraded"
-
-# install pipenv
-info "Installing 'pipenv'"
-pip install --upgrade pipenv || exit 1
-info "'pipenv' installed"
+info "Using 'uv': ${UV}"
 
 # check out submodules
 info "Checking out submodules"
@@ -118,7 +81,7 @@ mkdir -p local
 # build VTR
 info "Building VTR"
 cd vtr
-${MAKE} -j${MAKE_JOBCOUNT} CMAKE=${CMAKE} || exit 1
+${MAKE} -j${MAKE_JOBCOUNT} CMAKE="${CMAKE}" || exit 1
 cd ..
 info "VTR built successfully"
 
@@ -136,10 +99,13 @@ cp ../../vtr/build/utils/fasm/genfasm genfasm
 cd ../..
 info "'vpr' and 'genfasm' linked to ${PWD}/local/bin"
 
-# build a virtualenv for prga.py
+# build a virtualenv for prga.py using uv
 cd prga.py
-info "Creating a virtualenv for prga.py"
-PIPENV_VENV_IN_PROJECT=1 pipenv --python ${PYTHON_VERSION} install -e .[cocotb] || exit 1
+info "Creating a virtualenv for prga.py using uv"
+# uv will automatically fetch Python 3.8.2 if it's not installed, create the venv, and install deps
+[ -e .venv ] && rm -rf .venv
+uv venv --python ${PYTHON_VERSION} .venv || exit 1
+uv pip install -e .[cocotb] || exit 1
 cd ..
 info "Virtualenv setup completed for prga.py"
 
